//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_PUESTO_TRABAJO
    {
        public int ID_CAT_PUESTO_TRABAJO { get; set; }
        public string DESC_PUESTO { get; set; }
        public Nullable<int> ID_CAT_DEPARTAMENTO { get; set; }
    
        public virtual CAT_DEPARTAMENTO CAT_DEPARTAMENTO { get; set; }
    }
}
