//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GestionProyectosEntitie : DbContext
    {
        public GestionProyectosEntitie()
            : base("name=GestionProyectosEntitie")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_DEPARTAMENTO> CAT_DEPARTAMENTO { get; set; }
        public virtual DbSet<CAT_ESTATUS> CAT_ESTATUS { get; set; }
        public virtual DbSet<CAT_PRIORIDAD> CAT_PRIORIDAD { get; set; }
        public virtual DbSet<CAT_PUESTO_TRABAJO> CAT_PUESTO_TRABAJO { get; set; }
        public virtual DbSet<CAT_ROL> CAT_ROL { get; set; }
        public virtual DbSet<CAT_TIP_REQUERIMIENTO> CAT_TIP_REQUERIMIENTO { get; set; }
        public virtual DbSet<ESTADO> ESTADOes { get; set; }
        public virtual DbSet<LOGIN> LOGINS { get; set; }
        public virtual DbSet<PLANILLA_RRHH> PLANILLA_RRHH { get; set; }
        public virtual DbSet<PROYECTO> PROYECTOes { get; set; }
        public virtual DbSet<REQUERIMIENTO> REQUERIMIENTOes { get; set; }
        public virtual DbSet<TAREA> TAREAs { get; set; }
        public virtual DbSet<TECNICO> TECNICOes { get; set; }
    }
}
