//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLANILLA_RRHH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PLANILLA_RRHH()
        {
            this.LOGINS = new HashSet<LOGIN>();
            this.TECNICOes = new HashSet<TECNICO>();
            this.TAREAs = new HashSet<TAREA>();
        }
    
        public int ID_PLANILLA_RRHH { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> ID_CAT_PUESTO { get; set; }
        public string CORREO { get; set; }
        public Nullable<int> ID_CAT_ROL { get; set; }
        public string TELEFONO { get; set; }
    
        public virtual CAT_ROL CAT_ROL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOGIN> LOGINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TECNICO> TECNICOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAREA> TAREAs { get; set; }
    }
}
