//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROYECTO()
        {
            this.REQUERIMIENTOes = new HashSet<REQUERIMIENTO>();
        }
    
        public int ID_PROYECTO { get; set; }
        public string DESC_PROYECTO { get; set; }
        public Nullable<int> TECNICO_ID_TECNICO { get; set; }
        public Nullable<int> ESTADO_ID_ESTADO { get; set; }
        public Nullable<System.DateTime> TIEMPO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUERIMIENTO> REQUERIMIENTOes { get; set; }
        public virtual TECNICO TECNICO { get; set; }
    }
}
