//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REQUERIMIENTO
    {
        public int ID_TAREA { get; set; }
        public string DESC_TAREA { get; set; }
        public Nullable<int> PROYECTO_ID_PROYECTO { get; set; }
        public Nullable<int> ESTADO_ID_ESTADO { get; set; }
    
        public virtual ESTADO ESTADO { get; set; }
        public virtual PROYECTO PROYECTO { get; set; }
    }
}
