//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAREA
    {
        public int ID_TAREA { get; set; }
        public Nullable<int> ID_EMPLEADO { get; set; }
        public Nullable<int> ID_TIP_REQUERIMIENTO { get; set; }
        public string DESC_TAREA { get; set; }
        public Nullable<int> ID_PRIORIDAD { get; set; }
        public Nullable<int> ID_ESTADO { get; set; }
        public Nullable<System.DateTime> TIEMPO { get; set; }
    
        public virtual CAT_PRIORIDAD CAT_PRIORIDAD { get; set; }
        public virtual CAT_TIP_REQUERIMIENTO CAT_TIP_REQUERIMIENTO { get; set; }
        public virtual ESTADO ESTADO { get; set; }
        public virtual PLANILLA_RRHH PLANILLA_RRHH { get; set; }
    }
}
