//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TECNICO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TECNICO()
        {
            this.PROYECTOes = new HashSet<PROYECTO>();
        }
    
        public int ID_TECNICO { get; set; }
        public Nullable<int> PRH_ID_PLANILLA_RRHH { get; set; }
        public Nullable<int> PRH_ID_CAT_ROL { get; set; }
        public Nullable<int> PRH_ID_CAT_ESTATUS { get; set; }
    
        public virtual CAT_ESTATUS CAT_ESTATUS { get; set; }
        public virtual CAT_ROL CAT_ROL { get; set; }
        public virtual PLANILLA_RRHH PLANILLA_RRHH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROYECTO> PROYECTOes { get; set; }
    }
}
